#!/bin/bash
# osdetect - OS Detection via TTL Analysis
# Usage: osdetect <IP>

[[ $# -ne 1 ]] && echo "Usage: ${0##*/} <IP>" && exit 1

ip="$1"
timeout 2 ping -c1 "$ip" 2>/dev/null | grep -o 'ttl=[0-9]*' | cut -d= -f2 | {
    read ttl
    [[ -z "$ttl" ]] && echo "Error: Host unreachable" && exit 1
    
    case $ttl in
        12[0-9]|1[3-9][0-9]) os="Windows" ;;
        6[0-9]|5[0-9])       os="Linux" ;;
        25[0-5])             os="Solaris/Cisco" ;;
        *)                   os="Unknown" ;;
    esac
    
    echo "$ip (ttl:$ttl) -> $os"
}